--- # .periphery.yml
project: Periphery.xcodeproj
report_exclude:
  - Sources/PeripheryKit/Extensions/String+Version.swift
  - Sources/PeripheryKit/Indexer/SourceGraphDebugger.swift
schemes:
- Periphery
- Periphery-Package
targets:
- Periphery
- PeripheryKit
- PeripheryKitTests
