disabled_rules:
  - todo
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - identifier_name
  - file_length
  - function_parameter_count

excluded:
  - Tests/RetentionFixtures
  - Tests/SyntaxFixtures
  - .build
